### ISSUE TITLE
investigate uncovered code

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#210]
lines shown uncovered by tests:

line 20 in App.tsx https://github.com/mozilla/perfcompare/blob/staging/src/components/App.tsx#L20
clicking the close button in tests does not seem to affect coverage for this line

lines 8-10 in useQueryParams.ts: https://github.com/mozilla/perfcompare/blob/staging/src/hooks/useQueryParams.ts#L8-L10

coverage for useQueryParams was lost in patch #203 

I'm unsure what caused the change. I did try various approaches in the tests but they were still shown as uncovered.

**Comment by NikolaDojic** [comment]
the App coverage problem is solved if we render the `App` component instead of the `SearchView` component in https://github.com/mozilla/perfcompare/blob/bc909051e929ca29935d0b11ce2c8fd788766ef0/src/__tests__/Snackbar.test.tsx#L24
It is caused by the `closeSnackbar` call inside the onClick callback (`SnackbarCloseButton` component) not being covered by tests.

I've created a pr that fixes mentioned issues and provides test coverage for `useFetchCompareResults`
https://github.com/mozilla/perfcompare/pull/289
